#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
seqdepcov_plot v0.1.5

Author: Vanness Mach (Bear)

Purpose:
    Plot sequencing depth across a genome from a depth file
    (samtools depth output).

Usage:
    python seqdepcov_plotv0.1.5.py <depth_file> [output_prefix]

Output:
    <prefix>.pdf  — publication-ready vector (TrueType fonts, fonttype 42)
    <prefix>.svg  — fully editable vector
    <prefix>.png  — high-resolution raster preview (300 dpi)

Changes from v0.1.4:
    - Added matplotlib rcParams for fonttype 42 (PDF/PS) and svg.fonttype none
    - Ensures text is fully editable in Illustrator and Inkscape
    - Font fallback chain: Arial > Helvetica > DejaVu Sans
      Prevents font replacement prompt in Adobe Illustrator
    - Version bump to v0.1.5
"""

__version__ = "0.1.5"

import argparse
import sys
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from pathlib import Path

# Publication-safe font settings
# Must be set BEFORE any plt calls
mpl.rcParams["pdf.fonttype"]     = 42
mpl.rcParams["ps.fonttype"]      = 42
mpl.rcParams["svg.fonttype"]     = "none"
mpl.rcParams["font.family"]      = "sans-serif"
mpl.rcParams["font.sans-serif"]  = ["Arial", "Helvetica", "DejaVu Sans"]


def main():
    parser = argparse.ArgumentParser(
        description="Plot sequencing depth across genome from a depth file."
    )
    parser.add_argument(
        "depth",
        help="Depth file generated by samtools depth"
    )
    parser.add_argument(
        "prefix",
        nargs="?",
        help="Output prefix (default: depth filename without extension)"
    )
    args = parser.parse_args()

    depth_path = Path(args.depth)
    if not depth_path.exists():
        sys.exit(f"ERROR: depth file not found: {depth_path}")

    prefix = args.prefix if args.prefix else depth_path.stem.replace(".depth", "")

    positions = []
    depths = []

    with open(depth_path) as f:
        for line in f:
            if not line.strip():
                continue
            _, pos, dep = line.split()
            positions.append(int(pos))
            depths.append(int(dep))

    if not depths:
        sys.exit("ERROR: depth file is empty.")

    positions = np.array(positions)
    depths    = np.array(depths)

    genome_len = positions.max()
    mean_depth = depths.mean()
    min_depth  = depths.min()
    max_depth  = depths.max()

    # === FIGURE ===
    fig, ax = plt.subplots(figsize=(14, 4))

    ax.plot(
        positions,
        depths,
        linewidth=0.6,
        label="Sequencing depth"
    )

    ax.set_xlabel("Genome position (bp)")
    ax.set_ylabel("Sequencing depth")
    ax.set_title("Sequencing depth across genome")

    # Remove horizontal padding — depth line flush with axes
    ax.margins(x=0)

    # Legend: fixed position, no box
    ax.legend(
        loc="upper right",
        frameon=False
    )

    # Stats line: centered below x-axis, anchored to figure (not axes)
    stats_line = (
        f"Genome length: {genome_len:,} bp    "
        f"Mean depth: {mean_depth:.1f}\u00d7    "
        f"Min depth: {min_depth}\u00d7    "
        f"Max depth: {max_depth}\u00d7"
    )

    fig.text(
        0.5, 0.02,
        stats_line,
        ha="center",
        va="bottom",
        fontsize=9
    )

    # Manual layout — NO tight_layout()
    # Gives stable, predictable output across PNG / PDF / SVG
    fig.subplots_adjust(
        left=0.06,
        right=0.99,
        top=0.88,
        bottom=0.18
    )

    # Save outputs
    fig.savefig(f"{prefix}.pdf")
    fig.savefig(f"{prefix}.svg")
    fig.savefig(f"{prefix}.png", dpi=300)
    plt.close(fig)

    print("====================================")
    print("Sequencing depth plot generated")
    print(f"Version : {__version__}")
    print(f"Output  : {prefix}.pdf / .svg / .png")
    print("====================================")


if __name__ == "__main__":
    main()
